---------------------------------------------------------------------------------------------------
-- real_names_redo mod by A S Lewis, based on real_names by Extex101
--      https://github.com/axcore/real_names_redo
--      Licence: MIT
---------------------------------------------------------------------------------------------------
-- init.lua
--      Initialise the mod
---------------------------------------------------------------------------------------------------

local S = minetest.get_translator(minetest.get_current_modname())

---------------------------------------------------------------------------------------------------
-- Set up global variables
---------------------------------------------------------------------------------------------------

rn = {}

-- The contents of the config file, stored in a dictionary in the form
--      rn.config_dict[language_name] = language_type
-- (For more information, see the comments in load_names.lua)
rn.config_dict = {}

-- Lists of names for each language_type, stored in a dictionary in the form
--      rn.name_dict[language_name]["first_boy"] = list_of_names
--      rn.name_dict[language_name]["first_girl"] = list_of_names
--      rn.name_dict[language_name]["last"] = list_of_names
--      rn.name_dict[language_name]["last_girl"] = list_of_names
-- (For more information, see the comments in load_names.lua)
rn.name_dict = {}

-- The current language name (a key in rn.config_dict), e.g. "British"
rn.lang_name = nil
-- The current language type (the corresponding value in rn.config_dict) - one of the values
--      "western", "slavic" and "asian"
rn.lang_type = nil

-- The most recent first (given) and last (family/surname) names generated by the formspec
rn.first_name = ""
rn.last_name = ""
-- The most recent full name generated by the formspec, with the first/last names in the required
--      order, according to the value of rn.lang_type
rn.full_name = ""
-- Switch between "boy" and "girl" when the formspec buttons are clicked (but only the resulting
--      name is saved)
rn.current_gender = "boy"

---------------------------------------------------------------------------------------------------
-- Set mod name/version
---------------------------------------------------------------------------------------------------

rn.name = "real_names_redo"

rn.ver_max = 1
rn.ver_min = 0
rn.ver_rev = 0

rn.intllib = S

---------------------------------------------------------------------------------------------------
-- Import paths
---------------------------------------------------------------------------------------------------

-- (Data is written to the worldpath)
rn.data = minetest.get_mod_storage()
rn.path = minetest.get_modpath(minetest.get_current_modname())

---------------------------------------------------------------------------------------------------
-- Load names
---------------------------------------------------------------------------------------------------

-- Load lists of names from text files
dofile(rn.path .. "/load_names.lua")

-- Handle the formspec
dofile(rn.path .. "/form.lua")
-- Define actions
dofile(rn.path .. "/actions.lua")
-- Define callbacks
dofile(rn.path .. "/callbacks.lua")
-- Define functions
dofile(rn.path .. "/functions.lua")

-- Load rubenwardy's "Chat_Command_Builder"
dofile(rn.path .. "/chat_command_builder.lua")
-- Load chat commands to make the formspec appear, or to change a name directly
dofile(rn.path .. "/commands.lua")
